name: 'Setup crosstool-ng'
description: 'Install crosstool-ng and required packages'
inputs:
  version:
    description: 'ct-ng version'
    required: true
    default: '1.28.0'
runs:
  using: "composite"
  steps:
    - name: Echo action Path
      run: echo ${{github.action_path}}
      shell: bash
    - name: Restore crosstool-ng cache
      id: cache-crosstool-ng-restore
      uses: actions/cache/restore@v5
      with:
        path: ~/.local/lib/ct-ng
        key: crosstool-ng-${{ runner.os }}-${{ runner.arch }}-${{ inputs.version }}-${{ hashFiles('.github/actions/setup-crosstool-ng/install-crosstool.sh') }}
    - name: Install packages (Linux)
      run: | 
          sudo apt-get update && sudo apt-get install -y gcc g++ gperf bison flex texinfo help2man make libncurses5-dev \
          python3-dev autoconf automake libtool libtool-bin gawk wget bzip2 xz-utils unzip \
          patch libstdc++6 rsync git meson ninja-build
      shell: bash
      if: ${{ runner.os == 'Linux' }}
    - name: Install packages (macOS)
      run: | 
          brew install autoconf automake bash binutils gawk gnu-sed \
            gnu-tar help2man make meson ncurses ninja pkg-config texinfo libtool
      shell: bash
      if: ${{ runner.os == 'macOS' }}
    - name: Install crosstool-ng
      if: ${{ steps.cache-crosstool-ng-restore.outputs.cache-hit != 'true' }}
      env:
        CROSSTOOL_NG_VERSION: ${{ inputs.version }}
      run: |
        if [[ $RUNNER_OS == "macOS" ]]; then
          PATH="$PATH:$(brew --prefix)/opt/binutils/bin"
          export PATH
          CPPFLAGS="-I$(brew --prefix)/opt/ncurses/include -I$(brew --prefix)/opt/gettext/include"
          export CPPFLAGS
          LDFLAGS="-L$(brew --prefix)/opt/ncurses/lib -L$(brew --prefix)/opt/gettext/lib"
          export LDFLAGS
        fi
        ${{github.action_path}}/install-crosstool.sh --prefix="$HOME/.local/lib/ct-ng"
      shell: bash
    - name: Save crosstool-ng cache
      if: ${{ steps.cache-crosstool-ng-restore.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@v5
      with:
        path: ~/.local/lib/ct-ng
        key: ${{ steps.cache-crosstool-ng-restore.outputs.cache-primary-key }}
    - name: Add crosstool-ng to PATH
      run: |
        echo "$HOME/.local/lib/ct-ng/bin" >> "$GITHUB_PATH"
      shell: bash